PUT http://localhost:3001/api/quizzes/6939ad6db3d02a110f3dc5f6
content-type: application/json

    {
  "question": "The five highest peaks in Finland are all found in which northern region?",
    "correct_answer": "Lapland",
    "answers": [
      "Central Ostrobothnia",
      "Uusimaa",
      "Southwest Finland",
      "Lapland"
    ],
    "category": "Finland"
  }