PUT http://localhost:3001/api/quizzes/6939a96fb3d02a110f3dc5dc
content-type: application/json

    {
   "question": "What is the Swedish name for Helsinki?",
    "correct_answer": "Helsingfors",
    "answers": [
      "Helsingør",
      "Suomi",
      "Helsingfors",
      "Hesa"
    ],
    "category": "Finland"
  }